### ISSUE TITLE
Could not resolve any locations for breakpoint at ... with XCode 16

### ISSUE THREAD

**Issue by thlcodes** [nisargjhaveri/vscode-ios-debug#26]
Hi! 

Thanks for this great extension, now I can almost enjoy developing iOS now 😁 

I have one issue though: 
Having XCode 16 installed, when trying to debug via breakpoints, I get:
```
Could not resolve any locations for breakpoint at /Users/me/ios/App/Features/Materials.swift:31, 
but found a valid location at /Users/me/ios/App/Features/Materials.swift:31
```
which is odd since both paths are identical.
This comes whenever I add a breakpoint via VSCode.

This is my launch config:
```json
{
  "name": "Launch DEV",
  "type": "lldb",
  "request": "launch",
  "program": "~/Library/Developer/Xcode/DerivedData/App/Build/Products/Debug-${command:ios-debug.targetSdk}/App-DEV.app",
  "iosBundleId": "my.demo.app",
  "iosTarget": "select",
  "preLaunchTask": "xcodebuild-dev"
}
```

When I use the lldb cli directly it works just fine. 

Ony idea? 

Cheers
Thomas

**Comment by nisargjhaveri** [comment]
You can try setting the following if not tried already. It'll use the Xcode's version of lldb instead of the bundled one. See if that helps? I see that the CodeLLDB's lldb version has not been updated in a while.

`"lldb.library": "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/LLDB",`

**Comment by thlcodes** [comment]
I already did that. Sadly I have the same issue with and without this setting.
What puzzles me ist that both paths match exactly ...
